import os

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./bramble.db")

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
AI_MODEL = "claude-haiku-4-5-20251001"
AI_MAX_TOKENS = 120
AI_TIMEOUT = 5.0

# Game balance
STARTING_MONEY = 5000
STARTING_REP = 0
STARTING_UNITS = 3
RENT_CYCLE_DAYS = 30
SCENARIO_INTERVAL_MIN = 3
SCENARIO_INTERVAL_MAX = 5
WIN_REP = 1000
